### ISSUE TITLE
Issues with Keypoint Matching in Multi-view PCA Loss using Identically Named Keypoints from SLEAP

### ISSUE THREAD

**Issue by Freddie-Faulich** [paninski-lab/lightning-pose#194]
I'm working on a project that involves 8 different camera views and I want to aligning keypoints for using Multi-view PCA loss. The keypoints in my dataset were labeled using SLEAP, and they share the same names across all views (e.g., "left_ear" in all cameras).

I’m encountering an issue where it seems the identical names across different views might be causing problems in correctly matching the keypoints during the setup of the Multi-view PCA loss.

The error I’m seeing is:

--------------------------------------------------------------------------------
mirrored_column_matches parameters
--------------------
Error executing job with overrides: []
Traceback (most recent call last):
  File "/teamspace/studios/this_studio/macaques/lightning-pose/scripts/train_hydra.py", line 35, in train_model
    train(cfg)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/typeguard/__init__.py", line 1033, in wrapper
    retval = func(*args, **kwargs)
  File "/teamspace/studios/this_studio/macaques/lightning-pose/lightning_pose/train.py", line 53, in train
    pretty_print_cfg(cfg)
  File "/teamspace/studios/this_studio/macaques/lightning-pose/lightning_pose/utils/__init__.py", line 29, in pretty_print_cfg
    for k, v in val.items():
omegaconf.errors.ConfigAttributeError: ListConfig does not support attribute access
    full_key: mirrored_column_matches[items]
    object_type=list
--------------------------------------------------------------------------------

How should I correctly match keypoints across different views when they have identical names? Could the error above be caused by the way the keypoints are being referenced or configured? If so, what’s the recommended approach for setting up Multi-view PCA loss in this scenario?

Any guidance or examples would be greatly appreciated!

My current setup looks like this: 
mirrored_column_matches:  # Multi-view PCA loss
    - [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
    - [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
    - [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
    - [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
    - [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
    - [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
    - [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
    - [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]

**Comment by themattinthehatt** [comment]
@Freddie-Faulich your current setup *should* work, although you might need to run `git pull` and try again because I changed the way `mirrored_column_matches` gets parsed a couple weeks after the multiview merge [(see commit)](https://github.com/danbider/lightning-pose/commit/7f37d20abde557e0db828c5dbb9466b482544843) 

Alternatively, since the keypoints are all named the same, and in the same order, you can just provide a single list that gets applied to all views like so:
```
mirrored_column_matches: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
```

Let me know if one or both of those don't work for you!

**Comment by themattinthehatt** [comment]
@Freddie-Faulich just checking in on this, were you able to get this working?

**Comment by themattinthehatt** [comment]
closing due to inactivity
