### ISSUE TITLE
pandas incorrectly reads labels file when first row is empty

### ISSUE THREAD

**Issue by AarushShintre** [paninski-lab/lightning-pose#210]
Hi, I faced the following error when trying to run multi-stream models: 

using dlc image augmentation pipeline
Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/gangliaguardian/lightning-pose/scripts/train_hydra.py", line 35, in train_model
    train(cfg)
  File "/home/gangliaguardian/lightning-pose/lightning_pose/train.py", line 54, in train
    dataset = get_dataset(cfg=cfg, data_dir=data_dir, imgaug_transform=imgaug_transform)
  File "/home/gangliaguardian/lightning-pose/lightning_pose/utils/scripts.py", line 103, in get_dataset
    dataset = MultiviewHeatmapDataset(
  File "/home/gangliaguardian/lightning-pose/lightning_pose/data/datasets.py", line 382, in __init__
    self.dataset[view] = HeatmapDataset(
  File "/home/gangliaguardian/lightning-pose/lightning_pose/data/datasets.py", line 245, in __init__
    super().__init__(
  File "/home/gangliaguardian/lightning-pose/lightning_pose/data/datasets.py", line 85, in __init__
    self.keypoints = self.keypoints.reshape(self.keypoints.shape[0], -1, 2)
RuntimeError: shape '[19, -1, 2]' is invalid for input of size 361 

Here's the Config File: 
callbacks:
  anneal_weight:
    attr_name: total_unsupervised_importance
    init_val: 0.0
    increase_factor: 0.01
    final_val: 1.0
    freeze_until_epoch: 0

dali:
  general:
    seed: 123456

  base:
    train:
      sequence_length: 32
    predict:
      sequence_length: 96

  context:
    train:
      batch_size: 16
    predict:
      sequence_length: 96

data:
  # resize dimensions to streamline model creation
  # resize dimensions: we do this internally to accelerate training. make sure it's a multiple of 128.
  image_orig_dims:
    height: 540
    width: 720
  image_resize_dims:
    height: 384
    width: 384
  # ABSOLUTE path to data directory
  data_dir: /home/gangliaguardian/lightning-pose/data/test_chocolate_07_24/
  # ABSOLUTE path to unlabeled videos' directory
  video_dir: /home/gangliaguardian/lightning-pose/data/test_chocolate_07_24/videos/
  csv_file: 
    - view0.csv
    - view1.csv
    - view2.csv
  view_names:
    - view0
    - view1
    - view2
  # downsample heatmaps - 2 | 3
  downsample_factor: 2
  # total number of keypoints
  num_keypoints: 15
  # indicator to use 2-stage dynamic crop algorithm
  dynamic_crop: False
  # max allowed number of instances, i.e. 1 for single-animal, >1 for multiple animal
  num_max_instances: 1
  # keypoint names
  keypoint_names:
  - thumb_left
  - thumb_right
  - finger_1_left
  - finger_1_right
  - finger_2_left
  - finger_2_right
  - finger_3_left
  - finger_3_right
  - finger_4_left
  - finger_4_right
  - snout
  - mouth
  - dorsal_left
  - dorsal_right
  - head
  mirrored_column_matches: null

training:
  imgaug: dlc
  train_batch_size: 8
  val_batch_size: 1
  test_batch_size: 1
  train_prob: 0.95
  val_prob: 0.05
  train_frames: 1
  num_gpus: 1
  log_every_n_steps: 150
  check_val_every_n_epoch: 150
  num_workers: 4
  early_stop_patience: 3
  unfreezing_epoch: 20
  min_epochs: 500
  max_epochs: 500
  ckpt_every_n_epochs: 100
  gpu_id: 0
  rng_seed_data_pt: 0
  rng_seed_model_pt: 0
  lr_scheduler: multisteplr
  lr_scheduler_params:
    multisteplr:
      milestones: [150, 200, 250]
      gamma: 0.5

model:
  losses_to_use: []
  backbone: resnet50_animal_ap10k
  model_type: heatmap
  heatmap_loss_type: mse
  model_name: test
  checkpoint: null

losses:
  pca_multiview:
    log_weight: 5.0
    components_to_keep: 3
    epsilon: null
  pca_singleview:
    log_weight: 5.0
    components_to_keep: 0.99
    epsilon: null
  temporal:
    log_weight: 5.0
    epsilon: 20.0
    prob_threshold: 0.05

eval:
  hydra_paths: [" "]
  predict_vids_after_training: true
  save_vids_after_training: true
  fiftyone:
    dataset_name: test
    model_display_names: ["test_model"]
    launch_app_from_script: false
    remote: true
    address: 127.0.0.1
    port: 5151
  test_videos_directory: /home/gangliaguardian/lightning-pose/data/test_chocolate_07_24/videos/
  confidence_thresh_for_vid: 0.90

hydra:
  run:
    dir: data/test_1_final/models/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: data/test/test_1_final/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}

**Comment by themattinthehatt** [comment]
@AarushShintre do you have the same set/number of keypoints in each of your csv files?

**Comment by AarushShintre** [comment]
Yes, that’s correct

**Comment by themattinthehatt** [comment]
Update: after a back and forth with @AarushShintre we found the issue lies in pandas skipping empty rows in a csv file when the empty row immediately follows the header. I will edit the name of this issue and leave it open until we have a fix.
