### ISSUE TITLE
When I fuse two perspectives into one video, it works fine during training, but fails during inference.

### ISSUE THREAD

**Issue by wyclearnpy** [paninski-lab/lightning-pose#231]
My data is like this.
![img063](https://github.com/user-attachments/assets/a78012fa-e308-46a5-9030-959bb1ee1037)

The terminal output is：

Warning: the argument `seed` shadows a Pipeline constructor argument of the same name.
/opt/dali/dali/operators/reader/nvdecoder/nvdecoder.cc:199: Unable to decode file /home/WYC/datasets/LP_2cam_own/videos/13.mp4
Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/WYC/code_repo/lightning-pose/scripts/predict_new_vids.py", line 95, in predict_videos_in_dir
    export_predictions_and_labeled_video(
  File "/home/WYC/.conda/envs/LP/lib/python3.10/site-packages/typeguard/__init__.py", line 1033, in wrapper
    retval = func(*args, **kwargs)
  File "/home/WYC/code_repo/lightning-pose/lightning_pose/utils/scripts.py", line 722, in export_predictions_and_labeled_video
    preds_df = predict_single_video(
  File "/home/WYC/.conda/envs/LP/lib/python3.10/site-packages/typeguard/__init__.py", line 1033, in wrapper
    retval = func(*args, **kwargs)
  File "/home/WYC/code_repo/lightning-pose/lightning_pose/utils/predictions.py", line 425, in predict_single_video
    predict_loader = vid_pred_class()
  File "/home/WYC/code_repo/lightning-pose/lightning_pose/data/dali.py", line 490, in __call__
    return LitDaliWrapper(pipe, **args[self.train_stage][self.model_type])
  File "/home/WYC/code_repo/lightning-pose/lightning_pose/data/dali.py", line 175, in __init__
    super().__init__(*args, **kwargs)
  File "/home/WYC/.conda/envs/LP/lib/python3.10/site-packages/nvidia/dali/plugin/pytorch/__init__.py", line 224, in __init__
    self._first_batch = DALIGenericIterator.__next__(self)
  File "/home/WYC/.conda/envs/LP/lib/python3.10/site-packages/nvidia/dali/plugin/pytorch/__init__.py", line 239, in __next__
    outputs = self._get_outputs()
  File "/home/WYC/.conda/envs/LP/lib/python3.10/site-packages/nvidia/dali/plugin/base_iterator.py", line 385, in _get_outputs
    outputs.append(p.share_outputs())
  File "/home/WYC/.conda/envs/LP/lib/python3.10/site-packages/nvidia/dali/pipeline.py", line 1215, in share_outputs
    return self._pipe.ShareOutputs()
RuntimeError: Critical error in pipeline:
Error in GPU operator `nvidia.dali.fn.readers.video`,
which was used in the pipeline definition with the following traceback:

  File "/home/WYC/code_repo/lightning-pose/lightning_pose/data/dali.py", line 91, in video_pipe
    video = fn.readers.video(

encountered:

Video is too large in at least one dimension.
C++ context: [/opt/dali/dali/operators/reader/nvdecoder/cuvideodecoder.cc:231] 
Current pipeline object is no longer valid.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

What is the problem, and how can I solve it？

**Comment by themattinthehatt** [comment]
@wyclearnpy can you run `ffprobe /home/WYC/datasets/LP_2cam_own/videos/13.mp4` and paste the output here?

**Comment by themattinthehatt** [comment]
@wyclearnpy just checking in on this

**Comment by themattinthehatt** [comment]
closing due to inactivity
